@url = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwiaWF0IjoxNjUwNDk5MDk4fQ.7DSm5fWhddmxHCKWETH8y8EEdcX8Ji2pnXfqwDx2_s8

### Rrgister
POST {{url}}/users/register
content-type: application/json

{"username":"salman_mo","password":"123456","name":"salman"}


### login
POST {{url}}/users/login
content-type: application/json
token: {{token}}

{"username":"salman_mo","password":"123456","name":"salman"}


###Me
GET {{url}}/users/me
token: {{token}}


###create posts
POST {{url}}/posts
Content-Type: application/json
token: {{token}}

{"title": "created post", "content":"created content"}


###edit posts
PUT  {{url}}/posts/0
Content-Type: application/json
token: {{token}}

{"title": "test post-edit-", "content":"post one-edit-"}


###delete posts
DELETE {{url}}/posts/0
token: {{token}}


###get posts list
GET {{url}}/posts
token: {{token}}


###get post by id
GET {{url}}/posts/0
token: {{token}}