@url = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjE2NWU1OWM5MTY1MGExMzBlMDk1NiIsImlhdCI6MTY1MDU1MTc4NX0.wYijwaQSPBLXYK7tV5hpcbd6Fw7DTihrh4kiZElaIyM
@id = 626186c1827576e0378b09fb

### Rrgister
POST {{url}}/users/register
content-type: application/json

{"username":"salman_mo","password":"123456","name":"salman"}


### login
POST {{url}}/users/login
content-type: application/json
token: {{token}}

{"username":"salman_mo","password":"123456"}


###Me
GET {{url}}/users/me
token: {{token}}


###create posts
POST {{url}}/posts
Content-Type: application/json
token: {{token}}

{"title": "created post", "content":"created content"}


###edit posts
PUT  {{url}}/posts/{{id}}
Content-Type: application/json
token: {{token}}

{"title": "test post-edit-", "content":"post one-edit-"}


###delete posts
DELETE {{url}}/posts//{{id}}
token: {{token}}


###get posts list
GET {{url}}/posts
token: {{token}}


###get post by id
GET {{url}}/posts/{{id}}
token: {{token}}